[11/May/2019 20:03:55] "GET /jiangfei HTTP/1.1" 200 1296
[11/May/2019 20:03:55] "GET /static/grace_voice/%E4%B8%80.mp3 HTTP/1.1" 200 13176
[11/May/2019 20:04:09] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:04:10] "GET /jiangfei HTTP/1.1" 200 1272
[11/May/2019 20:04:10] "GET /static/grace_voice/%E4%B9%99.mp3 HTTP/1.1" 200 13824
[11/May/2019 20:04:18] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:04:18] "GET /jiangfei HTTP/1.1" 200 1272
[11/May/2019 20:04:19] "GET /static/grace_voice/%E4%BA%8C.mp3 HTTP/1.1" 200 14976
[11/May/2019 20:04:53] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:04:54] "GET /jiangfei HTTP/1.1" 200 1270
[11/May/2019 20:04:54] "GET /static/grace_voice/%E5%8D%81.mp3 HTTP/1.1" 200 15264
[11/May/2019 20:04:55] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:04:55] "GET /jiangfei HTTP/1.1" 200 1269
[11/May/2019 20:04:56] "GET /static/grace_voice/%E4%B8%81.mp3 HTTP/1.1" 200 13968
[11/May/2019 20:04:56] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:04:57] "GET /jiangfei HTTP/1.1" 200 1270
[11/May/2019 20:04:57] "GET /static/grace_voice/%E5%8E%82.mp3 HTTP/1.1" 200 15480
[11/May/2019 20:04:57] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:04:58] "GET /jiangfei HTTP/1.1" 200 1270
[11/May/2019 20:04:58] "GET /static/grace_voice/%E4%B8%83.mp3 HTTP/1.1" 200 15336
[11/May/2019 20:04:59] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:04:59] "GET /jiangfei HTTP/1.1" 200 1270
[11/May/2019 20:04:59] "GET /static/grace_voice/%E5%8D%9C.mp3 HTTP/1.1" 200 14112
[11/May/2019 20:05:00] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:05:00] "GET /jiangfei HTTP/1.1" 200 1269
[11/May/2019 20:05:01] "GET /static/grace_voice/%E4%BA%BA.mp3 HTTP/1.1" 200 14760
[11/May/2019 20:05:02] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:05:03] "GET /jiangfei HTTP/1.1" 200 1270
[11/May/2019 20:05:03] "GET /static/grace_voice/%E5%85%A5.mp3 HTTP/1.1" 200 12456
[11/May/2019 20:05:03] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:05:04] "GET /jiangfei HTTP/1.1" 200 1270
[11/May/2019 20:05:04] "GET /static/grace_voice/%E5%85%AB.mp3 HTTP/1.1" 200 14112
[11/May/2019 20:05:05] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:05:06] "GET /jiangfei HTTP/1.1" 200 1270
[11/May/2019 20:05:06] "GET /static/grace_voice/%E4%B9%9D.mp3 HTTP/1.1" 200 15048
[11/May/2019 20:05:07] "GET /accept_cmd_jiangfei?every=week&cmd=8&cmd=2 HTTP/1.1" 302 0
[11/May/2019 20:05:07] "GET /static/grace_voice/%E4%B8%83.mp3 HTTP/1.1" 200 15336
[11/May/2019 20:05:08] "GET /jiangfei HTTP/1.1" 302 0
[11/May/2019 20:05:08] "GET /jiangfei HTTP/1.1" 200 977
[11/May/2019 20:05:08] "GET /static/grace_voice/%E5%B7%B2%E5%A4%8D%E4%B9%A0.mp3 HTTP/1.1" 404 1709
[11/May/2019 20:05:12] "GET /jiangfei HTTP/1.1" 200 977
[11/May/2019 20:05:12] "GET /static/grace_voice/%E5%B7%B2%E5%A4%8D%E4%B9%A0.mp3 HTTP/1.1" 404 1709
Internal Server Error: /jinzu
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ed/learm/learngit/apps/HelloWorld/chinese_jinzu.py", line 97, in jinzu
    dump2file('language_voice_diction_chinese_jinzu/4web_restudy/every_year_info', every_year_info)
  File "/home/ed/learm/learngit/apps/MyPython3.py", line 255, in dump2file
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'language_voice_diction_chinese_jinzu/4web_restudy/every_year_info'
[11/May/2019 20:05:18] "GET /jinzu HTTP/1.1" 500 68562
Internal Server Error: /xiaoen
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ed/learm/learngit/apps/HelloWorld/chinese_xiaoen.py", line 97, in xiaoen
    dump2file('language_voice_diction_chinese_xiaoen/4web_restudy/every_year_info', every_year_info)
  File "/home/ed/learm/learngit/apps/MyPython3.py", line 255, in dump2file
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'language_voice_diction_chinese_xiaoen/4web_restudy/every_year_info'
[11/May/2019 20:05:51] "GET /xiaoen HTTP/1.1" 500 68594
